from __future__ import annotations
from sqlalchemy import String, Text, Integer, ForeignKey, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base

class User(Base):
    __tablename__="users"; id:Mapped[str]=mapped_column(String,primary_key=True); email:Mapped[str]=mapped_column(String,unique=True,index=True); password_hash:Mapped[str]=mapped_column(String); salt:Mapped[str]=mapped_column(String); created_at:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="ACTIVE")
class Session(Base):
    __tablename__="sessions"; token_hash:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); expires_at:Mapped[int]=mapped_column(Integer); created_at:Mapped[str]=mapped_column(String)
class Capture(Base):
    __tablename__="captures"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); text:Mapped[str]=mapped_column(Text); type:Mapped[str]=mapped_column(String,default="UNSORTED"); source:Mapped[str]=mapped_column(String,default="MANUAL"); status:Mapped[str]=mapped_column(String,default="OPEN"); created_at:Mapped[str]=mapped_column(String)
class ClarityMap(Base):
    __tablename__="clarity_maps"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); situation:Mapped[str]=mapped_column(Text); facts:Mapped[str]=mapped_column(Text,default="[]"); story:Mapped[str]=mapped_column(Text,default=""); emotion:Mapped[str]=mapped_column(Text,default=""); need:Mapped[str]=mapped_column(Text,default=""); missing:Mapped[str]=mapped_column(Text,default="[]"); observed:Mapped[str]=mapped_column(Text,default="[]"); hypothesis:Mapped[str]=mapped_column(Text,default=""); confidence:Mapped[str]=mapped_column(String,default="LOW"); evidence_for:Mapped[str]=mapped_column(Text,default="[]"); evidence_against:Mapped[str]=mapped_column(Text,default="[]"); unknown:Mapped[str]=mapped_column(Text,default="[]"); test_method:Mapped[str]=mapped_column(Text,default=""); validation_status:Mapped[str]=mapped_column(String,default="PENDING"); validation_correction:Mapped[str]=mapped_column(Text,default=""); ai_generated:Mapped[int]=mapped_column(Integer,default=0); created_at:Mapped[str]=mapped_column(String); updated_at:Mapped[str]=mapped_column(String)
class Hypothesis(Base):
    __tablename__="hypotheses"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); map_id:Mapped[str]=mapped_column(ForeignKey("clarity_maps.id",ondelete="CASCADE")); statement:Mapped[str]=mapped_column(Text); confidence:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default="PENDING"); created_at:Mapped[str]=mapped_column(String); validated_at:Mapped[str|None]=mapped_column(String,nullable=True)
class Evidence(Base):
    __tablename__="evidence"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); hypothesis_id:Mapped[str]=mapped_column(ForeignKey("hypotheses.id",ondelete="CASCADE")); direction:Mapped[str]=mapped_column(String); statement:Mapped[str]=mapped_column(Text); created_at:Mapped[str]=mapped_column(String)
class Validation(Base):
    __tablename__="validations"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); object_type:Mapped[str]=mapped_column(String); object_id:Mapped[str]=mapped_column(String); response:Mapped[str]=mapped_column(String); correction:Mapped[str]=mapped_column(Text,default=""); created_at:Mapped[str]=mapped_column(String)
class Task(Base):
    __tablename__="tasks"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); source_id:Mapped[str|None]=mapped_column(String,nullable=True); text:Mapped[str]=mapped_column(Text); next_action:Mapped[str]=mapped_column(Text,default=""); done_definition:Mapped[str]=mapped_column(Text,default=""); status:Mapped[str]=mapped_column(String,default="OPEN"); defer_count:Mapped[int]=mapped_column(Integer,default=0); created_at:Mapped[str]=mapped_column(String); completed_at:Mapped[str|None]=mapped_column(String,nullable=True)
class Action(Base):
    __tablename__="actions"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); source_map_id:Mapped[str|None]=mapped_column(ForeignKey("clarity_maps.id",ondelete="SET NULL"),nullable=True); task_id:Mapped[str|None]=mapped_column(ForeignKey("tasks.id",ondelete="SET NULL"),nullable=True); description:Mapped[str]=mapped_column(Text); done_definition:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String,default="OPEN"); started_at:Mapped[str]=mapped_column(String)
class Result(Base):
    __tablename__="results"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); action_id:Mapped[str]=mapped_column(ForeignKey("actions.id",ondelete="CASCADE")); outcome:Mapped[str]=mapped_column(Text); user_rating:Mapped[int|None]=mapped_column(Integer,nullable=True); completed_at:Mapped[str]=mapped_column(String)
class Learning(Base):
    __tablename__="learnings"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); action_id:Mapped[str]=mapped_column(ForeignKey("actions.id",ondelete="CASCADE")); statement:Mapped[str]=mapped_column(Text); created_at:Mapped[str]=mapped_column(String)
class Memory(Base):
    __tablename__="memories"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); type:Mapped[str]=mapped_column(String); content:Mapped[str]=mapped_column(Text); source:Mapped[str]=mapped_column(String,default=""); confidence:Mapped[str]=mapped_column(String,default=""); status:Mapped[str]=mapped_column(String,default="ACTIVE"); created_at:Mapped[str]=mapped_column(String); updated_at:Mapped[str]=mapped_column(String)
class DailyClosure(Base):
    __tablename__="daily_closures"; __table_args__=(UniqueConstraint("user_id","date"),); id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); date:Mapped[str]=mapped_column(String); closed:Mapped[str]=mapped_column(Text,default=""); open:Mapped[str]=mapped_column(Text,default=""); reason_open:Mapped[str]=mapped_column(Text,default=""); mental_load:Mapped[int|None]=mapped_column(Integer,nullable=True); energy:Mapped[int|None]=mapped_column(Integer,nullable=True); frustration:Mapped[int|None]=mapped_column(Integer,nullable=True); win:Mapped[str]=mapped_column(Text,default=""); created_at:Mapped[str]=mapped_column(String); updated_at:Mapped[str]=mapped_column(String)
class AuditLog(Base):
    __tablename__="audit_log"; id:Mapped[str]=mapped_column(String,primary_key=True); user_id:Mapped[str|None]=mapped_column(String,nullable=True,index=True); actor:Mapped[str]=mapped_column(String); action:Mapped[str]=mapped_column(String); object_type:Mapped[str]=mapped_column(String); object_id:Mapped[str|None]=mapped_column(String,nullable=True); metadata_json:Mapped[str]=mapped_column(Text,default="{}"); timestamp:Mapped[str]=mapped_column(String)
