(function(){
'use strict';
const APP='0.10-rc', SCHEMA=10, KEY='orev-universal-v0-10-rc';
const OLD=['orev-universal-v0-9-rc','orev-universal-v0-8-rc','orev-universal-v0-7-rc','orev-universal-v0-6-rc'];
const app=document.getElementById('app'), view=document.getElementById('view'), nav=document.getElementById('bottom-nav'), fallback=document.getElementById('boot-fallback');
let route='home', historyStack=[], errors=[], qaResults=[];
window.__OREV_BOOT_STATUS__='LOADING';

const now=()=>new Date().toISOString();
const uid=()=>`id_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`;
const safe=(v,n=20000)=>String(v==null?'':v).slice(0,n);
const esc=v=>safe(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const clone=v=>JSON.parse(JSON.stringify(v));
const normText=v=>safe(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const deepEqual=(a,b)=>JSON.stringify(a)===JSON.stringify(b);

function blank(){return{
  schemaVersion:SCHEMA,appVersion:APP,initialized:false,
  profile:{name:'',goal:'',areas:['Trabajo','Familia','Casa','Yo']},
  tasks:[],events:[],claritySessions:[],resources:[],settings:{focusMinutes:25},activeFocus:null,
  acceptance:{active:false,step:0,startedAt:null,fail:null,completedAt:null},created:now(),updated:now()
};}
function normalizeTask(x={}){
  const states=['AHORA','HOY','ESTA SEMANA','PUEDE ESPERAR','ESPERANDO','TERMINADO'];
  const priorities=['ALTA','MEDIA','BAJA'];
  const status=states.includes(x.status)?x.status:'HOY';
  return {id:safe(x.id||uid(),100),text:safe(x.text,5000),note:safe(x.note,10000),area:['Trabajo','Familia','Casa','Yo'].includes(x.area)?x.area:'Trabajo',status,priority:priorities.includes(x.priority)?x.priority:'MEDIA',date:safe(x.date,30),responsible:safe(x.responsible,200),origin:safe(x.origin||'manual',200),created:safe(x.created||now(),80),updated:safe(x.updated||now(),80),done:status==='TERMINADO'||!!x.done};
}
function normalizeEvent(x={}){return {id:safe(x.id||uid(),100),title:safe(x.title,5000),date:safe(x.date,40),note:safe(x.note,10000),taskId:safe(x.taskId,100),done:!!x.done,created:safe(x.created||now(),80),updated:safe(x.updated||now(),80)};}
function normalizeHypothesis(h){if(typeof h==='string')return{text:safe(h,5000),certeza:'BAJA'};h=h&&typeof h==='object'?h:{};return{text:safe(h.text,5000),certeza:['BAJA','MEDIA','ALTA'].includes(h.certeza)?h.certeza:'BAJA'};}
function normalizeMap(m={},i=0,relato='') {return {
  version:Number(m.version)||i+1,
  hechos:arr(m.hechos).map(v=>safe(v,5000)),
  relatos:arr(m.relatos).length?arr(m.relatos).map(v=>safe(v,10000)):(relato?[safe(relato,10000)]:[]),
  observaciones:arr(m.observaciones).map(v=>safe(v,5000)),
  interpretaciones:arr(m.interpretaciones).map(v=>safe(v,5000)),
  hipotesis:arr(m.hipotesis).map(normalizeHypothesis),
  informacionFaltante:arr(m.informacionFaltante).map(v=>safe(v,5000)),
  validation:['YES','PARTIAL','NO',null].includes(m.validation)?m.validation:null,
  correction:safe(m.correction,10000),preservedFrom:arr(m.preservedFrom).slice(0,50),created:safe(m.created||now(),80)
};}
function normalizeMicro(m){if(!m)return null;if(typeof m==='string')return{text:safe(m,5000),created:now(),status:'PENDING',result:''};return{text:safe(m.text,5000),created:safe(m.created||now(),80),status:['PENDING','WORKED','PARTIAL','DID_NOT_WORK'].includes(m.status)?m.status:'PENDING',result:safe(m.result,5000)};}
function normalizeSession(x={}){
  const relato=safe(x.relato||x.initial,20000);
  return {id:safe(x.id||uid(),100),created:safe(x.created||now(),80),updated:safe(x.updated||now(),80),status:x.status==='closed'?'closed':'active',currentStep:['questions','map','correction','technique','closed'].includes(x.currentStep)?x.currentStep:'questions',relato,questions:arr(x.questions).map(v=>safe(v,5000)),answers:arr(x.answers).map(v=>safe(v,10000)),maps:arr(x.maps).map((m,i)=>normalizeMap(m,i,relato)),validation:['YES','PARTIAL','NO',null].includes(x.validation)?x.validation:null,corrections:arr(x.corrections).map(v=>safe(v,10000)),technique:x.technique&&typeof x.technique==='object'?{id:safe(x.technique.id,100),name:safe(x.technique.name,200),reason:safe(x.technique.reason,1200),appliedAt:safe(x.technique.appliedAt||now(),80)}:null,microAction:normalizeMicro(x.microAction),followUp:safe(x.followUp,5000),closedAt:safe(x.closedAt,80)};
}
function normalizeFocus(f){if(!f||typeof f!=='object')return null;let status=String(f.status||'PAUSED').toUpperCase();if(!['RUNNING','PAUSED','FINISHED'].includes(status))status='PAUSED';return{taskId:safe(f.taskId,100),duration:Math.max(60,Number(f.duration)||1500),remaining:Math.max(0,Number(f.remaining)||0),status,startedAt:safe(f.startedAt||now(),80),updatedAt:safe(f.updatedAt||now(),80)};}
function normalizeState(o){const b=blank();o=o&&typeof o==='object'&&!Array.isArray(o)?o:{};b.initialized=!!o.initialized;b.profile=o.profile&&typeof o.profile==='object'?{name:safe(o.profile.name,500),goal:safe(o.profile.goal,5000),areas:arr(o.profile.areas).filter(a=>['Trabajo','Familia','Casa','Yo'].includes(a))}:b.profile;if(!b.profile.areas.length)b.profile.areas=['Trabajo','Familia','Casa','Yo'];b.tasks=arr(o.tasks||o.items).map(normalizeTask).filter(t=>t.text);b.events=arr(o.events).map(normalizeEvent).filter(e=>e.title);b.claritySessions=arr(o.claritySessions).map(normalizeSession);b.resources=arr(o.resources).map(r=>typeof r==='string'?{id:uid(),text:safe(r,5000),created:now()}:r);b.settings=Object.assign(b.settings,o.settings||{});b.activeFocus=normalizeFocus(o.activeFocus);b.acceptance=o.acceptance&&typeof o.acceptance==='object'?Object.assign(b.acceptance,o.acceptance):b.acceptance;b.created=safe(o.created||b.created,80);b.updated=now();return b;}
function logError(phase,e){errors.push({at:now(),phase,message:safe(e&&e.message||e,500)});errors=errors.slice(-20);}
window.onerror=(m,s,l,c,e)=>logError('window.onerror',e||m);
window.onunhandledrejection=e=>logError('unhandledrejection',e.reason||'promise');
function load(){try{let raw=localStorage.getItem(KEY);if(!raw){for(const k of OLD){raw=localStorage.getItem(k);if(raw)break;}}return normalizeState(raw?JSON.parse(raw):blank());}catch(e){logError('load',e);return blank();}}
let state=load();
function save(){state.schemaVersion=SCHEMA;state.appVersion=APP;state.updated=now();try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){logError('save',e);return false;}}
function set(html){view.innerHTML=html;window.scrollTo(0,0);}
function go(r){if(route!==r)historyStack.push(route);route=routes[r]?r:'home';render();}
function back(){route=historyStack.pop()||'home';render();}
function render(){try{if(!state.initialized&&!['diagnostics','settings','acceptance'].includes(route)){renderOnboarding();return;} (routes[route]||routes.home)();}catch(e){logError('render:'+route,e);set(`<div class="error"><b>OREV no pudo mostrar esta pantalla.</b><br>${esc(e.message||e)}</div><button class="action" data-route="home">Volver a Inicio</button>`);}}

function renderOnboarding(){set(`<h1>Bienvenido/a</h1><div class="card"><label for="obName">¿Cómo te llamas?</label><input id="obName" class="field" value="${esc(state.profile.name)}"><label for="obGoal">¿Qué quieres organizar principalmente?</label><textarea id="obGoal" class="field area">${esc(state.profile.goal)}</textarea><div class="notice">Tus datos del núcleo se guardan localmente.</div><button class="action primary" data-action="finish-onboarding">Empezar mi Centro</button></div>`);}
function home(){set(`<h1>Hola${state.profile.name?', '+esc(state.profile.name):''}</h1><div class="grid"><button class="action primary" data-route="clarity"><b>✨ Quiero ordenar lo que me pasa</b>Sesión OREV® persistente.</button><button class="action blue" data-route="today"><b>☀️ ¿Qué me toca hoy?</b>Prioriza sin inventar urgencias.</button><button class="action rose" data-route="capture"><b>➕ Capturar algo</b></button><button class="action terr" data-route="saturated"><b>🎯 Estoy saturada</b>Una sola siguiente acción.</button><button class="action sage" data-route="focus"><b>⏱️ Hiperfoco</b></button><button class="action" data-route="search"><b>🔎 Buscar</b></button><button class="action" data-route="acceptance"><b>🧭 Modo prueba final</b>Un solo recorrido lineal.</button></div>`);}
function listTasks(xs){if(!xs.length)return'<div class="guide">No hay tareas aquí todavía.</div>';return xs.map(t=>`<div class="item"><b>${esc(t.text)}</b><div class="muted">${esc(t.status)} · ${esc(t.priority)}</div><div class="row"><button class="chip" data-action="edit-task" data-id="${esc(t.id)}">Editar</button><button class="chip" data-action="toggle-task" data-id="${esc(t.id)}">${t.done?'Reabrir':'Terminar'}</button><button class="chip" data-action="delete-task" data-id="${esc(t.id)}">Eliminar</button></div></div>`).join('');}
function renderArea(area){set(`<h1>${esc(area)}</h1><button class="action primary" data-route="capture">Nueva tarea</button>${listTasks(state.tasks.filter(t=>t.area===area))}`);}
function tasks(){set(`<h1>Pendientes</h1><button class="action primary" data-route="capture">Nueva tarea</button>${listTasks(state.tasks)}`);}
function taskForm(t){t=t||normalizeTask({});set(`<h1>${t.text?'Editar tarea':'Capturar algo'}</h1><div class="card"><input id="tId" type="hidden" value="${esc(t.text?t.id:'')}"><label for="tText">Tarea</label><input id="tText" class="field" value="${esc(t.text)}"><label for="tArea">Área</label><select id="tArea" class="field">${['Trabajo','Familia','Casa','Yo'].map(v=>`<option ${t.area===v?'selected':''}>${v}</option>`).join('')}</select><label for="tStatus">Estado</label><select id="tStatus" class="field">${['AHORA','HOY','ESTA SEMANA','PUEDE ESPERAR','ESPERANDO'].map(v=>`<option ${t.status===v?'selected':''}>${v}</option>`).join('')}</select><label for="tPriority">Prioridad</label><select id="tPriority" class="field">${['ALTA','MEDIA','BAJA'].map(v=>`<option ${t.priority===v?'selected':''}>${v}</option>`).join('')}</select><input id="tDate" type="date" class="field" value="${esc(t.date)}"><input id="tResp" class="field" placeholder="Responsable" value="${esc(t.responsible)}"><textarea id="tNote" class="field area" placeholder="Nota">${esc(t.note)}</textarea><button class="action primary" data-action="save-task">Guardar</button></div>`);}
function rankedTasks(){const x=state.tasks.filter(t=>!t.done&&t.status!=='ESPERANDO');const r={AHORA:5,HOY:4,'ESTA SEMANA':3,'PUEDE ESPERAR':1},p={ALTA:3,MEDIA:2,BAJA:1};return x.sort((a,b)=>(r[b.status]||0)-(r[a.status]||0)||(p[b.priority]||0)-(p[a.priority]||0));}
function today(){const x=rankedTasks();set(`<h1>¿Qué me toca hoy?</h1><div class="guide">Se priorizó por estado y prioridad registrados. No se inventan fechas ni urgencias.</div><h3>Imprescindible</h3>${listTasks(x.slice(0,1))}<h3>Importantes</h3>${listTasks(x.slice(1,3))}<h3>Puede esperar</h3>${listTasks(x.slice(3,6))}`);}
function saturated(){const x=rankedTasks();if(!x.length){set('<h1>Estoy saturada</h1><div class="guide">Dime una sola cosa que tengas en la cabeza.</div><button class="action primary" data-route="capture">Capturar una cosa</button>');return;}set(`<h1>Una sola siguiente acción</h1><div class="card"><b>${esc(x[0].text)}</b><div class="subtle">Elegida por estado y prioridad registrados.</div></div>`);}
function remaining(f){if(!f)return 0;if(f.status!=='RUNNING')return f.remaining;return Math.max(0,f.remaining-Math.floor((Date.now()-new Date(f.updatedAt).getTime())/1000));}
function focus(){const f=state.activeFocus;if(f&&f.status==='RUNNING'){f.remaining=remaining(f);f.updatedAt=now();if(!f.remaining)f.status='FINISHED';save();}set(`<h1>Hiperfoco</h1><select id="focusTask" class="field"><option value="">Selecciona tarea</option>${state.tasks.filter(t=>!t.done).map(t=>`<option value="${esc(t.id)}">${esc(t.text)}</option>`).join('')}</select>${f?`<div class="ok">${esc(f.status)} · ${Math.ceil(f.remaining/60)} min</div><div class="row">${f.status==='RUNNING'?'<button class="chip" data-action="pause-focus">Pausar</button>':''}${f.status==='PAUSED'?'<button class="chip" data-action="resume-focus">Reanudar</button>':''}<button class="chip" data-action="finish-focus">Finalizar</button></div>`:'<button class="action primary" data-action="start-focus">Iniciar</button>'}`);}
function work(){set('<h1>Trabajo</h1><button class="action" data-route="tasks"><b>Pendientes</b></button><button class="action" data-route="agenda"><b>Agenda</b></button><div class="card"><b>Correo</b><span class="status blocked">EXTERNAL · NOT_CONFIGURED</span></div><div class="card"><b>PAI / Excel</b><span class="status blocked">BACKEND_REQUIRED</span></div><div class="card"><b>Clínica</b><span class="status blocked">BACKEND_REQUIRED</span></div>');}
function agenda(){set(`<h1>Agenda local</h1><div class="card"><input id="evId" type="hidden"><input id="evTitle" class="field" placeholder="Evento"><input id="evDate" type="datetime-local" class="field"><textarea id="evNote" class="field area" placeholder="Nota"></textarea><button class="action primary" data-action="save-event">Guardar evento</button></div>${state.events.map(e=>`<div class="item"><b>${esc(e.title)}</b><div class="muted">${esc(e.date)}</div><div class="row"><button class="chip" data-action="edit-event" data-id="${e.id}">Editar</button><button class="chip" data-action="toggle-event" data-id="${e.id}">${e.done?'Reabrir':'Completar'}</button><button class="chip" data-action="delete-event" data-id="${e.id}">Eliminar</button></div></div>`).join('')}`);}
function search(){set('<h1>Buscar</h1><input id="searchQ" class="field" placeholder="Buscar tareas, agenda o sesiones OREV"><button class="action primary" data-action="run-search">Buscar</button><div id="searchResults"></div>');}

function activeSession(){return state.claritySessions.find(s=>s.status==='active')||null;}
function questionFor(s){if(!s.answers.length)return'¿Qué parte necesitas comprender o decidir primero?';const latest=s.answers[s.answers.length-1];if(/miedo|rechazo|amor/i.test(latest))return'¿Qué ocurre concretamente cuando alguien muestra interés genuino por ti?';return'¿Qué dato, si lo supieras, cambiaría tu forma de ver esta situación?';}
function semanticFromCorrection(text){const n=normText(text),hyps=[],missing=[];if(n.includes('miedo')&&n.includes('rechazo'))hyps.push({text:'Podría existir temor al rechazo.',certeza:'BAJA'});if(n.includes('miedo')&&(n.includes('amor')||n.includes('vincul')))hyps.push({text:'Podría existir temor relacionado con vincularse afectivamente.',certeza:'BAJA'});if(hyps.length)missing.push('¿Qué ocurre concretamente cuando aparece alguien que sí muestra interés genuino?');return{hyps,missing};}
function buildMap(s,correction=''){
  const prev=s.maps[s.maps.length-1]||null,version=(prev?prev.version:0)+1,sem=semanticFromCorrection(correction);
  const hypotheses=sem.hyps.length?sem.hyps:[{text:'Puede haber varias piezas mezcladas que todavía necesitan validación.',certeza:'BAJA'}];
  return normalizeMap({version,hechos:[],relatos:[s.relato],observaciones:['La información disponible proviene del relato de la persona y requiere validación.'],interpretaciones:[],hipotesis:hypotheses,informacionFaltante:sem.missing.length?sem.missing:['Qué parte encaja, qué parte falta y qué necesitas decidir.'],validation:null,correction,preservedFrom:prev?[prev.version]:[],created:now()},version-1,s.relato);
}
function renderMap(s,map){return `<div class="card map-block"><h2>Mapa v${map.version}</h2><div><span class="pill">HECHO</span>${map.hechos.length?map.hechos.map(esc).join('<br>'):'Sin hechos adicionales confirmados.'}</div><div><span class="pill">RELATO</span>${map.relatos.map(esc).join('<br>')}</div><div><span class="pill">OBSERVACIÓN</span>${map.observaciones.map(esc).join('<br>')||'Sin observaciones adicionales.'}</div><div><span class="pill">INTERPRETACIÓN</span>${map.interpretaciones.map(esc).join('<br>')||'No se fija una interpretación sin validación.'}</div><div><span class="pill">HIPÓTESIS</span>${map.hipotesis.map(h=>`${esc(h.text)} [${esc(h.certeza)}]`).join('<br>')}</div><div><span class="pill">INFORMACIÓN FALTANTE</span>${map.informacionFaltante.map(esc).join('<br>')}</div>${map.correction?`<div class="notice">Corrección registrada: ${esc(map.correction)}</div>`:''}</div>`;}
function clarity(){let s=activeSession();if(!s){set('<h1>Quiero ordenar lo que me pasa</h1><div class="guide">Orientación estructurada local. No diagnostica. La interpretación asistida por IA aún no está conectada.</div><textarea id="clarityInitial" class="field area" placeholder="Cuéntame qué está pasando"></textarea><button class="action primary" data-action="start-clarity">Empezar</button><button class="action" data-route="clarity-history">Ver sesiones anteriores</button>');return;}
  let html='<h1>Sesión OREV®</h1><div class="guide">HECHO ≠ RELATO ≠ OBSERVACIÓN ≠ INTERPRETACIÓN ≠ HIPÓTESIS.</div><div class="card"><b>Relato</b>'+esc(s.relato)+'</div>';
  if(s.currentStep==='questions'){const q=s.questions[s.questions.length-1]||questionFor(s);if(!s.questions.length){s.questions.push(q);s.updated=now();save();}html+=`<div class="card"><b>${esc(q)}</b><textarea id="clarityAnswer" class="field area"></textarea><button class="action primary" data-action="answer-clarity">Responder y crear mapa</button></div>`;}
  if(s.maps.length){const m=s.maps[s.maps.length-1];html+=renderMap(s,m);if(s.currentStep==='map')html+='<div class="row"><button class="chip" data-action="validate-clarity" data-value="YES">SÍ</button><button class="chip" data-action="validate-clarity" data-value="PARTIAL">EN PARTE</button><button class="chip" data-action="validate-clarity" data-value="NO">NO</button></div>';if(s.currentStep==='correction')html+=`<div class="card"><b>${s.validation==='NO'?'¿Qué está incorrecto o no representa lo que quisiste decir?':'¿Qué parte sí encaja y qué parte falta o cambiarías?'}</b><textarea id="clarityCorrection" class="field area"></textarea><button class="action primary" data-action="save-correction">Actualizar mapa</button></div>`;if(s.currentStep==='technique')html+=renderTechnique(s);}
  html+='<button class="action" data-route="home">Salir a Inicio</button>';set(html);
}
function renderTechnique(s){if(!s.technique){return '<div class="card"><b>Orientación estructurada local</b><div class="subtle">La técnica se selecciona por reglas explícitas, no por IA.</div><button class="action primary" data-action="choose-technique">Proponer técnica</button></div>';}
  const m=s.microAction;return `<div class="card"><b>${esc(s.technique.name)}</b><div>${esc(s.technique.reason)}</div>${m?`<div class="ok"><b>Microacción</b>${esc(m.text)} · ${esc(m.status)}</div><div class="row"><button class="chip" data-action="micro-result" data-value="WORKED">Funcionó</button><button class="chip" data-action="micro-result" data-value="PARTIAL">En parte</button><button class="chip" data-action="micro-result" data-value="DID_NOT_WORK">No funcionó</button></div>`:'<button class="action primary" data-action="create-micro">Crear microacción</button>'}<button class="action" data-action="close-clarity">Cerrar sesión</button></div>`;}
function clarityHistory(){const closed=state.claritySessions.filter(s=>s.status==='closed');set(`<h1>Sesiones anteriores</h1>${closed.length?closed.map(s=>`<div class="card history-card"><b>${esc(s.created.slice(0,10))}</b><div>${esc(s.relato.slice(0,180))}</div><div class="subtle">${s.maps.length} mapa(s) · ${s.microAction?esc(s.microAction.status):'sin microacción'}</div></div>`).join(''):'<div class="guide">Todavía no hay sesiones cerradas.</div>'}`);}
function chooseTechnique(s){const text=normText([s.relato,...s.answers,...s.corrections].join(' '));let tech={id:'next-action',name:'Siguiente acción mínima',reason:'Se propone para convertir claridad parcial en un paso concreto.'};if(text.includes('muchas')||text.includes('mezclad'))tech={id:'classification',name:'Descarga + clasificación',reason:'Se propone porque aparecen varias piezas mezcladas.'};if(text.includes('miedo')||text.includes('rechazo'))tech={id:'control-no-control',name:'Control / no control',reason:'Se propone porque hay una hipótesis relacional todavía no confirmada y conviene separar lo que depende de ti de lo que no.'};s.technique={...tech,appliedAt:now()};s.currentStep='technique';s.updated=now();save();render();}

function settings(){set(`<h1>Ajustes</h1><div class="card"><b>Versión</b>v0.10 RC</div><button class="action" data-action="export-backup">Exportar respaldo JSON</button><button class="action" data-action="import-backup">Importar respaldo JSON</button><input id="backupFile" type="file" accept="application/json" hidden><button class="action" data-route="acceptance">🧭 Modo prueba final</button>`);}
function diagnostics(){runQA();const rows=qaResults.map(q=>`<div class="card"><b>${esc(q.name)}</b><span class="status ${q.status==='PASS'?'pass':q.status==='FAIL'?'blocked':'pending'}">${esc(q.level)} · ${esc(q.status)}</span><div class="subtle">${esc(q.detail)}</div></div>`).join('');set(`<h1>🧪 Diagnóstico técnico</h1><div class="ok"><b>BOOT</b> ${esc(window.__OREV_BOOT_STATUS__)}</div>${rows}<div class="card"><b>Errores runtime</b>${errors.length}</div><div class="card"><b>Correo real</b><span class="status blocked">EXTERNAL · NOT_CONFIGURED</span></div><div class="card"><b>Calendar real</b><span class="status blocked">EXTERNAL · NOT_CONFIGURED</span></div><div class="card"><b>Drive privado</b><span class="status blocked">EXTERNAL · NOT_CONFIGURED</span></div><div class="card"><b>PAI / Excel</b><span class="status blocked">BACKEND_REQUIRED</span></div><div class="card"><b>Backend clínico</b><span class="status blocked">BACKEND_REQUIRED</span></div>`);}
function acceptance(){const steps=['Onboarding/perfil','Crear tarea','Editar tarea','Crear evento','Mi día','Estoy saturada','Hiperfoco','Buscar','OREV Mapa v1','OREV EN PARTE → Mapa v2','Salir/volver y recargar','Cerrar sesión y verificar historial'];const a=state.acceptance||blank().acceptance;const pct=Math.round((a.step/steps.length)*100);set(`<h1>🧭 Prueba final</h1><div class="guide">Un solo recorrido lineal. Si algo falla, registra el paso y detén solo este recorrido.</div><div class="meter"><span style="width:${pct}%"></span></div><div class="card qa-step"><strong>Paso ${Math.min(a.step+1,steps.length)}/${steps.length}</strong><span>${esc(steps[Math.min(a.step,steps.length-1)])}</span></div>${a.fail?`<div class="error"><b>FAIL</b>${esc(a.fail)}</div>`:''}${a.completedAt?'<div class="ok"><b>PRUEBA COMPLETA</b></div>':`<button class="action primary" data-action="acceptance-next">Marcar paso como correcto y continuar</button><button class="action" data-action="acceptance-fail">Registrar FAIL en este paso</button>`}<button class="action" data-action="acceptance-reset">Reiniciar prueba</button>`);}

const routes={home,work,family:()=>renderArea('Familia'),house:()=>renderArea('Casa'),me:()=>renderArea('Yo'),diagnostics,settings,capture:()=>taskForm(null),tasks,agenda,today,saturated,focus,search,clarity,'clarity-history':clarityHistory,acceptance};

function runQA(){qaResults=[];const push=(id,name,level,status,detail)=>qaResults.push({id,name,level,status,detail,timestamp:now(),appVersion:APP});
  try{const b=blank(),n=normalizeState(b);push('state-normalize','Estado normalizable','STATE',n.schemaVersion===SCHEMA?'PASS':'FAIL','Esquema '+n.schemaVersion);}catch(e){push('state-normalize','Estado normalizable','STATE','FAIL',e.message);}
  try{localStorage.setItem('__orev_test','1');const ok=localStorage.getItem('__orev_test')==='1';localStorage.removeItem('__orev_test');push('storage','Storage local','PERSISTENCE',ok?'PASS':'FAIL','Round-trip set/get/remove');}catch(e){push('storage','Storage local','PERSISTENCE','FAIL',e.message);}
  try{const s=normalizeSession({relato:'Prueba',answers:['Respuesta'],maps:[buildSyntheticMap(1,'Prueba','')],validation:'PARTIAL',corrections:['Corrección']});const round=normalizeSession(JSON.parse(JSON.stringify(s)));push('orev-rehydrate','OREV rehidratación sintética','PERSISTENCE',deepEqual(s,round)?'PASS':'FAIL','Comparación profunda normalizada');}catch(e){push('orev-rehydrate','OREV rehidratación sintética','PERSISTENCE','FAIL',e.message);}
  try{const f=normalizeFocus({taskId:'x',duration:1500,remaining:500,status:'PAUSED',startedAt:now(),updatedAt:now()});const r=normalizeFocus(JSON.parse(JSON.stringify(f)));push('focus-rehydrate','Hiperfoco rehidratable','STATE',deepEqual(f,r)?'PASS':'FAIL','Estado de foco estable');}catch(e){push('focus-rehydrate','Hiperfoco rehidratable','STATE','FAIL',e.message);}
  try{const x=esc('<script>alert(1)</script>');push('xss-escape','HTML escapable','SECURITY',x.includes('&lt;script&gt;')?'PASS':'FAIL','Contenido se trata como texto');}catch(e){push('xss-escape','HTML escapable','SECURITY','FAIL',e.message);}
  const critical=['home','work','diagnostics','tasks','agenda','clarity','settings'];push('routes','Rutas críticas registradas','SELF',critical.every(k=>typeof routes[k]==='function')?'PASS':'FAIL','Comprobación estática; no equivale a BROWSER PASS');
  push('browser-human','Interacción Samsung Internet','HUMAN','PASS','Evidencia humana previa: Inicio/Diagnóstico/Trabajo respondieron en v0.8/v0.9; v0.10 requiere aceptación final.');
}
function buildSyntheticMap(v,relato,correction){return normalizeMap({version:v,relatos:[relato],observaciones:['Observación'],hipotesis:[{text:'Hipótesis',certeza:'BAJA'}],informacionFaltante:['Dato faltante'],correction},v-1,relato);}

function exportBackup(){const payload={schemaVersion:SCHEMA,appVersion:APP,date:now(),state:clone(state)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`orev-backup-v010-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function validateBackup(obj){if(!obj||typeof obj!=='object'||Array.isArray(obj))throw new Error('Formato inválido');if(Number(obj.schemaVersion)>SCHEMA)throw new Error('Backup de una versión futura');if(!obj.state||typeof obj.state!=='object')throw new Error('Falta state');return true;}
async function importBackup(file){const before=clone(state);try{const text=await file.text(),obj=JSON.parse(text);validateBackup(obj);const candidate=normalizeState(obj.state);state=candidate;if(!save())throw new Error('No se pudo guardar');render();alert('Respaldo restaurado correctamente.');}catch(e){state=before;save();logError('restore',e);alert('No se importó el respaldo: '+e.message);}}

function startAcceptance(){state.acceptance={active:true,step:0,startedAt:now(),fail:null,completedAt:null};save();}
function acceptanceNext(){if(!state.acceptance.active)startAcceptance();state.acceptance.step+=1;if(state.acceptance.step>=12){state.acceptance.step=12;state.acceptance.completedAt=now();}save();render();}

function handleAction(action,el){
  if(action==='back')return back();
  if(action==='finish-onboarding'){state.profile.name=safe(document.getElementById('obName').value,500);state.profile.goal=safe(document.getElementById('obGoal').value,5000);state.initialized=true;save();return go('home');}
  if(action==='save-task'){const text=safe(document.getElementById('tText').value,5000).trim();if(!text)return alert('Escribe una tarea.');const idv=document.getElementById('tId').value;let t=idv?state.tasks.find(x=>x.id===idv):null;const data={text,area:document.getElementById('tArea').value,status:document.getElementById('tStatus').value,priority:document.getElementById('tPriority').value,date:document.getElementById('tDate').value,responsible:document.getElementById('tResp').value,note:document.getElementById('tNote').value};if(t){Object.assign(t,normalizeTask(Object.assign({},t,data,{id:t.id,updated:now()})));}else state.tasks.push(normalizeTask(data));save();return go('tasks');}
  if(action==='edit-task'){const t=state.tasks.find(x=>x.id===el.dataset.id);if(t)return taskForm(t);}
  if(action==='toggle-task'){const t=state.tasks.find(x=>x.id===el.dataset.id);if(t){t.done=!t.done;t.status=t.done?'TERMINADO':'HOY';t.updated=now();save();render();}return;}
  if(action==='delete-task'){state.tasks=state.tasks.filter(x=>x.id!==el.dataset.id);save();return render();}
  if(action==='save-event'){const title=safe(document.getElementById('evTitle').value,5000).trim();if(!title)return alert('Escribe un evento.');const idv=document.getElementById('evId').value;let e=idv?state.events.find(x=>x.id===idv):null;const data={title,date:document.getElementById('evDate').value,note:document.getElementById('evNote').value};if(e)Object.assign(e,normalizeEvent(Object.assign({},e,data,{id:e.id,updated:now()})));else state.events.push(normalizeEvent(data));save();return agenda();}
  if(action==='edit-event'){const e=state.events.find(x=>x.id===el.dataset.id);if(e){agenda();document.getElementById('evId').value=e.id;document.getElementById('evTitle').value=e.title;document.getElementById('evDate').value=e.date;document.getElementById('evNote').value=e.note;}return;}
  if(action==='toggle-event'){const e=state.events.find(x=>x.id===el.dataset.id);if(e){e.done=!e.done;e.updated=now();save();agenda();}return;}
  if(action==='delete-event'){state.events=state.events.filter(x=>x.id!==el.dataset.id);save();return agenda();}
  if(action==='start-focus'){const taskId=document.getElementById('focusTask').value;if(!taskId)return alert('Selecciona una tarea.');const d=Math.max(60,Number(state.settings.focusMinutes||25)*60);state.activeFocus={taskId,duration:d,remaining:d,status:'RUNNING',startedAt:now(),updatedAt:now()};save();return focus();}
  if(action==='pause-focus'){if(state.activeFocus){state.activeFocus.remaining=remaining(state.activeFocus);state.activeFocus.status='PAUSED';state.activeFocus.updatedAt=now();save();}return focus();}
  if(action==='resume-focus'){if(state.activeFocus){state.activeFocus.status='RUNNING';state.activeFocus.updatedAt=now();save();}return focus();}
  if(action==='finish-focus'){if(state.activeFocus){state.activeFocus.status='FINISHED';state.activeFocus.remaining=0;state.activeFocus.updatedAt=now();save();}return focus();}
  if(action==='run-search'){const q=normText(document.getElementById('searchQ').value),out=[];state.tasks.forEach(t=>{if(normText(t.text+' '+t.note).includes(q))out.push('Tarea: '+t.text)});state.events.forEach(e=>{if(normText(e.title+' '+e.note).includes(q))out.push('Agenda: '+e.title)});state.claritySessions.forEach(s=>{if(normText(s.relato).includes(q))out.push('OREV: '+s.relato.slice(0,120))});document.getElementById('searchResults').innerHTML=out.length?out.map(x=>`<div class="item">${esc(x)}</div>`).join(''):'<div class="guide">Sin resultados.</div>';return;}
  if(action==='start-clarity'){const relato=safe(document.getElementById('clarityInitial').value,20000).trim();if(!relato)return alert('Escribe qué está pasando.');let s=activeSession();if(!s){s=normalizeSession({id:uid(),relato,status:'active',currentStep:'questions'});state.claritySessions.push(s);}save();return clarity();}
  if(action==='answer-clarity'){const s=activeSession(),a=safe(document.getElementById('clarityAnswer').value,10000).trim();if(!a)return alert('Escribe una respuesta.');s.answers.push(a);s.maps.push(buildMap(s,''));s.currentStep='map';s.updated=now();save();return clarity();}
  if(action==='validate-clarity'){const s=activeSession(),m=s.maps[s.maps.length-1],v=el.dataset.value;m.validation=v;s.validation=v;s.updated=now();if(v==='YES')s.currentStep='technique';else s.currentStep='correction';save();return clarity();}
  if(action==='save-correction'){const s=activeSession(),c=safe(document.getElementById('clarityCorrection').value,10000).trim();if(!c)return alert('Escribe qué cambiarías.');const prev=s.maps[s.maps.length-1];prev.correction=c;s.corrections.push(c);s.maps.push(buildMap(s,c));s.currentStep='map';s.updated=now();save();return clarity();}
  if(action==='choose-technique'){return chooseTechnique(activeSession());}
  if(action==='create-micro'){const s=activeSession();s.microAction={text:'Define una acción pequeña que puedas realizar y observar.',created:now(),status:'PENDING',result:''};s.updated=now();save();return clarity();}
  if(action==='micro-result'){const s=activeSession();if(s&&s.microAction){s.microAction.status=el.dataset.value;s.microAction.result='Resultado registrado por la persona.';if(el.dataset.value==='WORKED')state.resources.push({id:uid(),text:s.technique.name,context:s.relato.slice(0,200),result:'WORKED',created:now()});s.updated=now();save();}return clarity();}
  if(action==='close-clarity'){const s=activeSession();if(s){s.status='closed';s.currentStep='closed';s.closedAt=now();s.updated=now();save();}return go('clarity-history');}
  if(action==='export-backup')return exportBackup();
  if(action==='import-backup'){document.getElementById('backupFile').click();return;}
  if(action==='acceptance-next')return acceptanceNext();
  if(action==='acceptance-fail'){const msg=prompt('Describe brevemente qué falló en este paso.');if(msg){state.acceptance.fail=`Paso ${state.acceptance.step+1}: ${safe(msg,1000)}`;save();render();}return;}
  if(action==='acceptance-reset'){startAcceptance();return render();}
}

document.addEventListener('click',e=>{const routeEl=e.target.closest('[data-route]');if(routeEl){e.preventDefault();return go(routeEl.dataset.route);}const actionEl=e.target.closest('[data-action]');if(actionEl){e.preventDefault();return handleAction(actionEl.dataset.action,actionEl);}});
document.addEventListener('change',e=>{if(e.target&&e.target.id==='backupFile'&&e.target.files&&e.target.files[0])importBackup(e.target.files[0]);});

try{window.__OREV_BOOT_STATUS__='READY';fallback.hidden=true;app.hidden=false;nav.hidden=false;render();}catch(e){window.__OREV_BOOT_STATUS__='ERROR';logError('boot',e);fallback.innerHTML=`<div class="error"><b>OREV no pudo iniciar.</b><br>${esc(e.message||e)}</div>`;}
})();
